<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="sukeerthsahana" failures="2" tests="9" name="dsAlgoTests.DataStructureTest" time="57.650" errors="0" timestamp="2025-02-13T13:41:59 CST" skipped="2">
  <testcase classname="dsAlgoTests.DataStructureTest" name="navigatetoTimeComplexitytryeditor" time="6.733"/>
  <system-out/>
  <testcase classname="dsAlgoTests.DataStructureTest" name="verifyCodeExecutionforDataStructureIntroductionPage" time="7.078"/>
  <system-out/>
  <testcase classname="dsAlgoTests.DataStructureTest" name="navigateToDataStructureIntroductionPagePracticeQuestions" time="5.479"/>
  <system-out/>
  <testcase classname="dsAlgoTests.DataStructureTest" name="verifyCodeExecutionforDataStructureIntroductionPage" time="7.209"/>
  <system-out/>
  <testcase classname="dsAlgoTests.DataStructureTest" name="seeListOfPracticeQuestionsonDataStructureIntroductionPage" time="5.649">
    <failure message="No practice questions found on the Practice Questions Page!" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No practice questions found on the Practice Questions Page!
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.DataStructureTest.seeListOfPracticeQuestionsonDataStructureIntroductionPage(DataStructureTest.java:71)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- seeListOfPracticeQuestionsonDataStructureIntroductionPage -->
  <system-out/>
  <testcase classname="dsAlgoTests.DataStructureTest" name="seeListOfPracticeQuestionsonDataStructureIntroductionPage" time="6.120">
    <skipped/>
  </testcase> <!-- seeListOfPracticeQuestionsonDataStructureIntroductionPage -->
  <system-out/>
  <testcase classname="dsAlgoTests.DataStructureTest" name="checkErrorMessageWhenExecutingWithoutCodeInDataStructureIntroductionPage" time="6.301">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed.
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.DataStructureTest.checkErrorMessageWhenExecutingWithoutCodeInDataStructureIntroductionPage(DataStructureTest.java:81)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeInDataStructureIntroductionPage -->
  <system-out/>
  <testcase classname="dsAlgoTests.DataStructureTest" name="checkErrorMessageWhenExecutingWithoutCodeInDataStructureIntroductionPage" time="7.394">
    <skipped/>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeInDataStructureIntroductionPage -->
  <system-out/>
  <testcase classname="dsAlgoTests.DataStructureTest" name="navigatetoTimeComplexityModule" time="5.687"/>
  <system-out/>
</testsuite> <!-- dsAlgoTests.DataStructureTest -->
