<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="sukeerthsahana" failures="5" tests="24" name="dsAlgoTests.QueueTest" time="169.288" errors="0" timestamp="2025-02-05T16:54:42 CST" skipped="0">
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToPracticeQuestionImplementationUsingCollectionsDeque" time="6.592"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigatetoImplementationOfQueueInPython" time="6.634"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToQueueOperationsTryEditor" time="6.601"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigatetoImplementationUsingCollectionsDeque" time="5.857"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="7.777"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="7.483"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToImplementationUsingArray" time="6.113"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationOfQueueInPython" time="7.682">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.QueueTest.checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationOfQueueInPython(QueueTest.java:135)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationOfQueueInPython -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigatetoImplementationUsingCollectionsDequeTryEditor" time="7.098"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMessageWhenExecutingWithoutCodeInImplementationUsingCollectionsDeque" time="6.979">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.QueueTest.checkErrorMessageWhenExecutingWithoutCodeInImplementationUsingCollectionsDeque(QueueTest.java:142)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMessageWhenExecutingWithoutCodeInImplementationUsingCollectionsDeque -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMeaasgeWhenExecutingWithoutCodeInQueueOperations" time="6.853">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.QueueTest.checkErrorMeaasgeWhenExecutingWithoutCodeInQueueOperations(QueueTest.java:156)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMeaasgeWhenExecutingWithoutCodeInQueueOperations -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="7.354"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationUsingArray" time="7.639">
    <failure message="Test failed: Expected an error message when clicking the &#039;Run&#039; button without entering code, but no message was displayed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed: Expected an error message when clicking the 'Run' button without entering code, but no message was displayed
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.QueueTest.checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationUsingArray(QueueTest.java:149)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkErrorMeaasgeWhenExecutingWithoutCodeInImplementationUsingArray -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="7.476"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="8.505"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToImplementationUsingArrayTryEditor" time="6.674"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="listOfPracticeQuestionImplementationUsingCollectionsDeque" time="6.682"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigatetoImplementationOfQueueInPythonTryEditor" time="7.453"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="listOfPracticeQuestionOfImplementationOfQueueInPython" time="6.464">
    <failure message="No list of practice question found" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No list of practice question found
at org.testng.Assert.fail(Assert.java:99)
at dsAlgoTests.QueueTest.listOfPracticeQuestionOfImplementationOfQueueInPython(QueueTest.java:112)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- listOfPracticeQuestionOfImplementationOfQueueInPython -->
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToPracticeQuestionOfImplementationOfQueueInPython" time="6.542"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="7.309"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="navigateToQueueOperations" time="6.595"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="7.585"/>
  <system-out/>
  <testcase classname="dsAlgoTests.QueueTest" name="verifyCodeExecutionForQueueTryEditor" time="7.341"/>
  <system-out/>
</testsuite> <!-- dsAlgoTests.QueueTest -->
